using System.Security.Cryptography;
using System.Text;
using Game.ServiceDefaults;

namespace Game.Gateway.Endpoints;

/// <summary>
/// Quest Lab Tome — the web-facing version of the in-game spellbook, generated by
/// tools/component-packets/render_quest_lab.py.
///
/// Serving follows <see cref="WorkbenchViewEndpoints"/> rather than the read-once-at-startup
/// pattern it used to: the document is re-read per request behind an mtime-and-length cache, and
/// <c>LUMBERJACKS_QUESTLAB_HTML</c> relocates it, so a corrected tome can be mounted over the copy
/// built into the image and republished by file copy — no image rebuild, no restart. Before this,
/// fixing a sentence in the tome meant cutting a Gateway release, which is why the page went so
/// long without telling anyone how to install the mod it documents.
///
/// Resolution degrades in steps — mounted asset, then the copy built into the image, then the
/// fallback page — so a missing mount costs freshness, not the page. Every response carries the
/// SHA-256 of the file on disk in <c>X-QuestLab-Sha256</c>, so a served page can be verified
/// byte-for-byte against the committed artifact.
/// </summary>
public static class QuestLabViewEndpoints
{
    // Two segments, not "Community/questlab.html": Path.Combine keeps an embedded forward slash
    // verbatim, so the one-string form only resolves on Linux. Same trap as the workbench asset.
    private const string AssetDirectory = "Community";
    private const string AssetFile = "questlab.html";
    private const string PathVariable = "LUMBERJACKS_QUESTLAB_HTML";
    private const string ShaHeader = "X-QuestLab-Sha256";

    private const string FallbackHtml =
        "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>Lumberjacks — Quest Lab Tome</title></head>" +
        "<body style=\"background:#0b1013;color:#edf5f2;font-family:system-ui,sans-serif;padding:2rem\">" +
        "<h1>Quest Lab Tome unavailable</h1>" +
        "<p>The generated tome was not included in this Gateway build. Run " +
        "<code>python tools/component-packets/render_quest_lab.py</code> and publish again, or read " +
        "<code>network/mod/ComfyQuestLab/README.md</code> directly.</p>" +
        "</body></html>";

    /// <summary>A resolved tome plus the stat fields that decide whether it is stale.</summary>
    private sealed record Document(string Path, DateTime WriteTimeUtc, long Length, string Html, string Sha256);

    private static Document? cache;

    public static void Map(WebApplication app)
    {
        var contentRoot = app.Environment.ContentRootPath;
        var logger = app.Logger;

        app.MapGet("/questlab", (HttpContext context) =>
            {
                var document = Load(contentRoot, logger);
                context.Response.Headers[ShaHeader] = document.Sha256;
                return Results.Text(document.Html, "text/html; charset=utf-8");
            })
            .RequireCors(PublicTelemetryV0.CorsPolicyName);
    }

    /// <summary>
    /// Prefers a mounted asset, but only once it is actually present: an absent or empty mount
    /// falls through to the copy built into the image rather than to the unavailable page.
    /// </summary>
    public static string ResolvePath(string contentRoot) =>
        Environment.GetEnvironmentVariable(PathVariable) is { Length: > 0 } configured && File.Exists(configured)
            ? configured
            : Path.Combine(contentRoot, AssetDirectory, AssetFile);

    private static Document Load(string contentRoot, ILogger logger)
    {
        var path = ResolvePath(contentRoot);
        var (writeTimeUtc, length) = Stat(path);

        var cached = Volatile.Read(ref cache);
        if (cached is not null && cached.Path == path && cached.WriteTimeUtc == writeTimeUtc && cached.Length == length)
        {
            return cached;
        }

        Document document;
        try
        {
            var bytes = File.ReadAllBytes(path);
            document = new Document(path, writeTimeUtc, length, Decode(bytes), Sha256(bytes));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            logger.LogWarning(ex,
                "Could not load {Path} for GET /questlab — serving a minimal fallback page instead.", path);
            document = new Document(path, writeTimeUtc, length, FallbackHtml, Sha256(Encoding.UTF8.GetBytes(FallbackHtml)));
        }

        // A losing racer re-reads the same file and writes an equal document; the race is benign.
        Volatile.Write(ref cache, document);
        return document;
    }

    /// <summary>Stat fields for a file, or (MinValue, -1) when it is absent or unreadable.</summary>
    private static (DateTime WriteTimeUtc, long Length) Stat(string path)
    {
        try
        {
            var info = new FileInfo(path);
            return info.Exists ? (info.LastWriteTimeUtc, info.Length) : (DateTime.MinValue, -1L);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return (DateTime.MinValue, -1L);
        }
    }

    // Strip a UTF-8 BOM the way File.ReadAllText would; a leading U+FEFF would otherwise render
    // as page content. The hash stays over the raw bytes so it matches the artifact.
    private static string Decode(byte[] bytes) =>
        bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF
            ? Encoding.UTF8.GetString(bytes, 3, bytes.Length - 3)
            : Encoding.UTF8.GetString(bytes);

    private static string Sha256(byte[] bytes) => Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
}
