namespace Lumberjacks.Companion;

static class QuestStudioPage
{
    public const string Html = """
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Quest Studio</title><style>
:root{color-scheme:dark;--ink:#eee8d4;--muted:#aaad9e;--panel:#191d22;--line:#3b4446;--gold:#d7aa57;--green:#6dc69e;--red:#e08373}*{box-sizing:border-box}body{max-width:1080px;margin:28px auto;padding:0 18px;background:#101418;color:var(--ink);font:15px system-ui}h1{margin-bottom:4px;color:var(--gold)}h2{margin-top:0}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:18px;margin:16px 0}.grimoire{border-color:#79633a;background:linear-gradient(145deg,#211f1a,#191d22)}label{display:block;margin:11px 0 5px;color:#d9d4bd;font-weight:650}input,select,textarea{width:100%;padding:10px;border-radius:7px;border:1px solid #525b5d;background:#101419;color:var(--ink);font:inherit}textarea{min-height:84px;resize:vertical}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:16px}button,a.btn{border:0;border-radius:7px;padding:10px 14px;background:#886b32;color:white;font-weight:700;cursor:pointer;text-decoration:none}button.secondary,a.secondary{background:transparent;border:1px solid #626d70}.status{border-left:4px solid var(--gold)}.status.ok{border-left-color:var(--green)}.status.bad{border-left-color:var(--red)}pre{white-space:pre-wrap;overflow:auto;background:#0b0e11;padding:13px;border-radius:8px;max-height:330px}.stage{padding:16px;border:1px solid #725f3a;border-radius:10px;background:#151714}.arrow{text-align:center;color:var(--gold);font-size:25px}@media(max-width:720px){.grid{grid-template-columns:1fr}}
</style></head><body>
<h1>Quest Studio</h1><p class="muted">The browser Grimoire begins with one complete, bounded experience. Nothing changes in Valheim until Runtime Check and Load.</p>
<p><a class="btn secondary" href="/workbench">← Workbench</a></p>
<div class="grid"><section class="card grimoire"><h2>Experience</h2>
<label for="pack">Pack ID</label><input id="pack" maxlength="64"><label for="version">Semantic version</label><input id="version" placeholder="1.0.0">
<label for="experience">Experience ID</label><input id="experience" maxlength="64"><label for="title">Title</label><input id="title" maxlength="120">
<label for="event">Grimoire event</label><select id="event"></select><label for="target">Target (optional)</label><input id="target" maxlength="120">
<label for="message">Message action</label><textarea id="message" maxlength="500"></textarea>
<div class="actions"><button onclick="save()">Save draft</button><button class="secondary" onclick="certify()">Certify</button><button onclick="publishProject()">Publish to Game</button></div></section>
<section><div class="card"><h2>Graph preview</h2><div class="stage"><strong id="stage-title">Start</strong><p id="stage-trigger"></p></div><div class="arrow">↓</div><div class="stage"><strong>Complete</strong><p id="stage-action"></p></div></div>
<div class="card status" id="status"><h2 id="status-title">Loading Studio…</h2><p id="status-text" class="muted"></p><pre id="details" hidden></pre></div><div class="card"><h2>Version history and diff</h2><p class="muted">Immutable certified snapshots from durable Studio state.</p><div class="grid"><select id="diff-from"></select><select id="diff-to"></select></div><div class="actions"><button class="secondary" onclick="compareVersions()">Compare versions</button></div><div id="history">No saved versions yet.</div><pre id="diff" hidden></pre></div><div class="card"><h2>Runtime receipts</h2><p class="muted">Updated when this page refreshes; no live game connection.</p><div id="receipts">No receipts yet.</div></div></section></div>
<script>
const q=s=>document.querySelector(s);let token='';const fields=['pack','version','experience','title','event','target','message'];
async function api(url,opt={}){let r=await fetch(url,{cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(token?{'X-Workbench-Token':token}:{}),...(opt.headers||{})}});let d=await r.json();if(!r.ok)throw d;return d}
function project(){return{pack_id:q('#pack').value.trim(),version:q('#version').value.trim(),experience_id:q('#experience').value.trim(),title:q('#title').value.trim(),event:q('#event').value,target:q('#target').value.trim()||null,message:q('#message').value.trim()}}
function paint(p){q('#pack').value=p.pack_id;q('#version').value=p.version;q('#experience').value=p.experience_id;q('#title').value=p.title;q('#event').value=p.event;q('#target').value=p.target||'';q('#message').value=p.message;preview()}
function preview(){q('#stage-title').textContent=q('#title').value||'Start';q('#stage-trigger').textContent='When '+(q('#event').value||'an event')+(q('#target').value?' matches '+q('#target').value:'');q('#stage-action').textContent='Message: '+(q('#message').value||'…')}
function status(ok,title,text,data){let e=q('#status');e.className='card status '+(ok?'ok':'bad');q('#status-title').textContent=title;q('#status-text').textContent=text||'';q('#details').hidden=!data;q('#details').textContent=data?JSON.stringify(data,null,2):''}
async function mutate(path){try{let d=await api(path,{method:'POST',body:JSON.stringify(project())});status(true,d.status==='published'?'Published to Runtime inbox':'Certified',d.receipt?`${d.receipt.pack_id} ${d.receipt.version} · ${d.receipt.content_hash}`:`content ${d.content_hash}`,d);if(path.includes('save')||path.includes('publish'))await loadHistory();return d}catch(e){status(false,'Studio rejected the project',e.error||'Validation failed',e)}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadHistory(){try{let d=await api('/api/v1/workbench/quest-studio/history'),v=d.versions||[],options=v.map(x=>`<option value="${x.content_hash}">${esc(x.project.version)} · ${esc(x.project.title)} · ${x.content_hash.slice(0,8)}</option>`).join('');q('#diff-from').innerHTML=options;q('#diff-to').innerHTML=options;if(v.length>1)q('#diff-from').selectedIndex=1;q('#history').innerHTML=v.length?v.map(x=>`<p><strong>${esc(x.project.version)}</strong> · ${esc(x.project.title)}<br><span class="muted">${esc(x.saved_utc)} · ${x.content_hash.slice(0,12)}</span></p>`).join(''):'No saved versions yet.'}catch(e){q('#history').textContent='History unavailable.'}}
async function compareVersions(){try{let from=q('#diff-from').value,to=q('#diff-to').value;if(!from||!to)return;let d=await api('/api/v1/workbench/quest-studio/diff?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to));q('#diff').hidden=false;q('#diff').textContent=d.changes.length?d.changes.map(x=>`${x.field}\n- ${x.from??''}\n+ ${x.to??''}`).join('\n\n'):'No semantic changes.'}catch(e){status(false,'Diff unavailable',e.error||'Version could not be compared.',e)}}
async function loadReceipts(){try{let d=await api('/api/v1/workbench/quest-studio/receipts');q('#receipts').innerHTML=d.receipts.length?d.receipts.slice(0,8).map(r=>`<p><strong>${r.operation}</strong> · ${r.status} · ${r.pack_id||''} ${r.version||''}<br><span class="muted">${r.at_utc}${r.error?' · '+r.error:''}</span></p>`).join(''):(d.available?'No Runtime receipts yet.':'Valheim is unavailable; manual copy remains available.')}catch(e){q('#receipts').textContent='Receipts unavailable.'}}
async function save(){return mutate('/api/v1/workbench/quest-studio/save')}async function certify(){return mutate('/api/v1/workbench/quest-studio/certify')}async function publishProject(){return mutate('/api/v1/workbench/quest-studio/publish-project')}
async function init(){try{token=(await api('/api/v1/workbench/security')).browser_token;let events=await api('/api/v1/workbench/quest-studio/events');q('#event').innerHTML=events.events.map(x=>`<option value="${x}">${x.replaceAll('_',' ')}</option>`).join('');paint(await api('/api/v1/workbench/quest-studio/project'));fields.forEach(x=>q('#'+x).addEventListener('input',preview));status(true,'Draft ready','Save, certify, or publish this single-stage experience.');loadReceipts();loadHistory()}catch(e){status(false,'Studio unavailable',e.error||String(e),e)}}init();
</script></body></html>
""";
}
