static class WorkbenchV1Page
{
    public const string Html = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Baseline Workbench</title>
  <style>.hidden{display:block!important}</style>
  <style>
    :root{color-scheme:dark;--bg:#0e131a;--card:#18212c;--line:#304052;--text:#e8edf4;--muted:#9eacbd;--blue:#43a6ff;--green:#63d391;--amber:#ffce75;--red:#ff9585}
    *{box-sizing:border-box}body{max-width:1280px;margin:0 auto;padding:22px 18px;background:var(--bg);color:var(--text);font:15px system-ui,sans-serif}h1{margin:0;color:var(--blue)}h2{margin:0 0 10px}h3{margin:0 0 7px;color:#c4dcf7}.muted{color:var(--muted)}.small{font-size:.87rem}.source,code,pre{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.source{color:#b9d9fb}.nav{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.nav a,.button{border:1px solid #55708d;border-radius:8px;padding:8px 12px;background:#1d4f7b;color:#fff;text-decoration:none;cursor:pointer;font:inherit}.nav a.secondary,.button.secondary{background:transparent}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px}.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px;margin:12px 0}.hero{border-color:#317bb9}.tile{background:#111922;border:1px solid var(--line);border-radius:9px;padding:12px}.first-visit{margin:12px 0}.first-visit ol{margin:8px 0;padding-left:22px}.first-visit li{margin:5px 0}.ok{border-color:#2d8655}.wait{border-color:#93732e}.bad{border-color:#8b443a}.tag{display:inline-block;border-radius:999px;padding:2px 8px;background:#2a3746;color:#dce8f7;font-size:.82rem}.tag.ok{background:#16462d;color:#b8f2ce}.tag.wait{background:#51401c;color:#ffdf9d}.tag.bad{background:#51251f;color:#ffc1b8}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.toolbar input{background:#0d141c;border:1px solid var(--line);border-radius:7px;padding:9px;color:var(--text)}pre{white-space:pre-wrap;overflow:auto;background:#0a0e13;border-radius:8px;padding:12px}.hidden{display:none}.cap{display:flex;flex-direction:column;gap:7px}.cap .button{align-self:flex-start}.pill{color:var(--muted)}@media(max-width:650px){body{padding:14px 10px}.grid{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <header class="card hero">
    <div class="toolbar"><div><h1>Baseline Workbench</h1><p id="subtitle" class="muted">Your local ownership and control surface.</p></div><div style="margin-left:auto"><span id="profile" class="tag wait">loading</span> <span id="claim-state" class="tag wait">loading</span></div></div>
    <div class="nav"><a href="#home">Home</a><a href="#explore">Explore</a><a href="#build">Build</a><a href="#operate">Operate</a><a href="#recover">Recover</a><a href="#community">Community</a><button id="mode" class="button secondary" onclick="toggleMode()">Standard</button><a class="secondary" href="/trace">Trace</a><a class="secondary" href="/roadmap">Roadmap</a></div>
    <p id="privacy" class="small muted">Privacy posture loading.</p>
  </header>

  <section id="home" class="card"><h2>Home</h2><p id="objective" class="muted">Loading the local projection…</p><aside id="first-visit" class="tile first-visit"><h3>First visit: start safely</h3><ol><li>Read the system map. Green is ready; amber is excluded, waiting, or not configured; red needs attention.</li><li>Open Explore and run <strong>Inspect system</strong>. It is read-only.</li><li>Find the new job under Jobs and open its events or receipt.</li><li>If recovery is needed, use a support export or safe recreate. Factory reset is intentionally separate.</li></ol><a class="button secondary" href="#explore">Start with Explore</a></aside><p id="source" class="source">Source identity loading…</p><div id="topology" class="grid"></div></section>
  <section id="explore" class="card"><h2>Explore</h2><p class="muted">Understand the installation, its targets, and its evidence before changing anything.</p><div class="toolbar"><button class="button" onclick="startJob('explore.system.inspect')">Inspect system</button><button class="button secondary" onclick="refresh()">Refresh</button></div><pre id="inspect-result">No inspection job started.</pre></section>
  <section id="build" class="card"><h2>Build</h2><p class="muted">Developer and Lab capabilities appear only when the launcher selected the matching profile.</p><div id="build-caps" class="grid"></div></section>
  <section id="operate" class="card"><h2>Operate</h2><p class="muted">Stable maintenance capabilities remain separate from the development control plane.</p><div id="operate-caps" class="grid"></div></section>
  <section id="recover" class="card"><h2>Recover</h2><p class="muted">Snapshots and support exports are recoverable artifacts. Recreate is not factory reset.</p><div id="recover-caps" class="grid"></div></section>
  <section id="community" class="card"><h2>Community</h2><p class="muted">This local surface is the source for safe support and orientation. Public sharing is explicit and privacy-gated.</p><a class="button secondary" href="/community">Open community surface</a></section>
  <section class="card"><h2>Installation</h2><div id="claim-box"></div><h2 style="margin-top:18px">Jobs</h2><div id="jobs" class="grid"></div></section>
  <details class="card"><summary>Raw Workbench projection</summary><pre id="raw">Loading…</pre></details>

  <script>
    let projection=null, token=null, advanced=localStorage.getItem('baseline.workbench.mode')==='advanced';
    const q=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const get=async u=>{let r=await fetch(u,{cache:'no-store'});let d=await r.json();if(!r.ok)throw d;return d};
    function tag(s){let c=['ready','working','complete','succeeded','success'].includes(String(s).toLowerCase())?'ok':(['queued','waiting_dependency','waiting_human','offline','not_configured','excluded'].includes(String(s).toLowerCase())?'wait':'bad');return '<span class="tag '+c+'">'+esc(s)+'</span>'}
    function toggleMode(){advanced=!advanced;localStorage.setItem('baseline.workbench.mode',advanced?'advanced':'standard');paint(projection)}
    function paint(p){
      projection=p;q('#profile').textContent=p.profile.effective;q('#claim-state').textContent=p.installation.claimed?'owned':'Explore / unclaimed';q('#claim-state').className='tag '+(p.installation.claimed?'ok':'wait');q('#mode').textContent=advanced?'Advanced':'Standard';q('#source').textContent='revision '+(p.source.source_revision||'unknown')+' · branch '+(p.source.source_branch||'unknown')+' · image '+(p.source.image||'unknown')+' · dirty '+p.source.source_dirty;q('#objective').textContent=p.installation.claimed?'This installation is configured to be yours. Choose a capability, target, and evidence boundary.':'Explore safely first, then claim this local installation to enable stable Admin capabilities.';
      q('#topology').innerHTML=(p.topology.nodes||[]).map(n=>'<article class="tile '+(n.state==='ready'||n.state==='working'?'ok':(n.state==='excluded'||n.state==='waiting_dependency'||n.state==='not_configured'?'wait':'bad'))+'"><h3>'+esc(n.title)+'</h3><div>'+tag(n.state)+'</div><p class="small">'+esc(n.role)+'<br>target: '+esc(n.target)+'<br>human touch: '+esc(n.human_touch)+'</p><p class="small muted">'+esc(n.source)+' · '+esc(n.observed_utc||'not observed')+'</p></article>').join('');
      let caps=p.capabilities||[];q('#build-caps').innerHTML=caps.filter(c=>c.intent==='Build').map(capabilityCard).join('')||'<p class="muted">No Build capabilities are eligible in this profile.</p>';q('#operate-caps').innerHTML=caps.filter(c=>c.intent==='Operate').map(capabilityCard).join('')||'<p class="muted">No Operate capabilities are eligible in this profile.</p>';q('#recover-caps').innerHTML=caps.filter(c=>c.intent==='Recover').map(capabilityCard).join('')||'<p class="muted">No Recover capabilities are eligible in this profile.</p>';
      q('#jobs').innerHTML=(p.jobs||[]).map(j=>'<article class="tile"><h3>'+esc(j.title)+'</h3><div>'+tag(j.state)+'</div><p class="small">'+esc(j.job_id)+'<br>'+esc(j.capability_id)+' · '+esc(j.target)+'</p><p class="small muted">'+esc(j.reason_code||'')+' '+esc(j.updated_utc||'')+'</p>'+(j.state==='queued'||j.state==='leased'?'<button class="button secondary" onclick="cancelJob(\''+esc(j.job_id)+'\')">Cancel</button>':'')+'</article>').join('')||'<p class="muted">No jobs yet.</p>';q('#raw').textContent=JSON.stringify(p,null,2);
      q('#claim-box').innerHTML=p.installation.claimed?'<p class="ok">Owned installation <code>'+esc(p.installation.installation_id)+'</code>.</p>':'<div class="toolbar"><input id="owner-label" maxlength="80" placeholder="Optional local label"><button class="button" onclick="claim()">Claim this installation</button></div><p class="small muted">Claiming is local-only and does not store Steam credentials.</p>';
    }
    async function refresh(){try{paint(await get('/api/v1/workbench'))}catch(e){q('#raw').textContent='Workbench projection unavailable: '+JSON.stringify(e)}}
    async function claim(){let r=await fetch('/api/v1/workbench/installation/claim',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify({label:q('#owner-label')?.value||null})});if(!r.ok){alert('Claim failed: '+await r.text());return}await refresh()}
    async function cancelJob(id){let r=await fetch('/api/v1/workbench/jobs/'+encodeURIComponent(id)+'/cancel',{method:'POST',headers:{'X-Workbench-Token':token}});if(!r.ok){alert('Cancel refused: '+await r.text());return}await refresh()}
    // Standard/Advanced is presentation only: capability eligibility stays visible and is
    // always decided by the server registry. These wrappers add typed prompts without
    // granting a browser any capability it was not already offered by the API.
    function capabilityCard(c){let disabled=!c.eligible;let target=(c.eligible_targets||[])[0]||'local';let label=c.read_only?'Standard capability':'Advanced capability';return '<article class="tile cap '+(disabled?'wait':'')+'"><h3>'+esc(c.title)+'</h3><div>'+tag(c.eligible?'available':c.reason_code)+' <span class="pill small">'+label+'</span></div><p class="small muted">'+esc(c.id)+' | '+esc(c.side_effect)+' | human: '+esc(c.human_touch)+'</p><p class="small">profiles: '+esc((c.eligible_profiles||[]).join(', '))+'<br>targets: '+esc((c.eligible_targets||[]).join(', '))+'<br>privacy: '+esc(c.privacy_class||'private_local')+'</p>'+(!disabled?'<button class="button" onclick="startJob(\''+esc(c.id)+'\',\''+esc(target)+'\')">Start</button>':'')+'</article>'}
    async function startJob(id,target){let inputs={};if(id==='recover.recreate.verify'){if(prompt('Type RECREATE to confirm safe recreate (volume is retained)')!=='RECREATE')return;inputs.confirm_recreate=true}if(id==='operate.mod.install'||id==='operate.mod.rollback'){if(prompt('Type I CLOSED VALHEIM to continue')!=='I CLOSED VALHEIM')return;inputs.game_closed_confirmed=true}let r=await fetch('/api/v1/workbench/capabilities/'+encodeURIComponent(id)+'/jobs',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify({target:target||'local',inputs})});let d=await r.json();if(!r.ok){alert('Job refused: '+JSON.stringify(d));return}q('#inspect-result').textContent=JSON.stringify(d,null,2);await refresh()}
     async function observe(id){let outcome=prompt('Observation outcome: pass or fail','pass');if(!['pass','fail'].includes(outcome))return;let role=prompt('Role following: followed, mixed, or did_not_follow','followed');if(!['followed','mixed','did_not_follow'].includes(role))return;let quality=prompt('Rendered quality: smooth, mixed, or rough','smooth');if(!['smooth','mixed','rough'].includes(quality))return;let note=prompt('Optional private operator note (500 chars max)','');let r=await fetch('/api/v1/workbench/jobs/'+encodeURIComponent(id)+'/observation',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify({outcome,role_following:role,quality,operator_note:note||null,cleanup_confirmed:true})});if(!r.ok){alert('Observation refused: '+await r.text());return}await refresh()}
     function decorateWorkbenchEvidence(p){(p.jobs||[]).forEach(j=>{let cards=[...document.querySelectorAll('#jobs .tile')];let card=cards.find(x=>x.textContent.includes(j.job_id));if(!card)return;let links=card.querySelector('.job-evidence');if(!links){links=document.createElement('p');links.className='small job-evidence';links.innerHTML='<a href="/api/v1/workbench/jobs/'+encodeURIComponent(j.job_id)+'/events" target="_blank" rel="noreferrer">events</a>'+(j.receipt_path? ' · <a href="/api/v1/workbench/jobs/'+encodeURIComponent(j.job_id)+'/receipt" target="_blank" rel="noreferrer">receipt</a>':'');card.appendChild(links)}if(j.artifacts?.length&&!card.querySelector('.job-artifacts')){let a=document.createElement('p');a.className='small muted job-artifacts';a.textContent='artifacts: '+j.artifacts.map(x=>x.name+' ['+x.privacy_class+']').join(', ');card.appendChild(a)}});(p.topology?.nodes||[]).filter(n=>n.active_job_phase).forEach(n=>{let cards=[...document.querySelectorAll('#topology .tile')];let card=cards.find(x=>x.textContent.includes(n.title));if(card&&!card.querySelector('.active-phase')){let phase=document.createElement('p');phase.className='small wait active-phase';phase.textContent='active job: '+n.active_job_phase;card.appendChild(phase)}})}
     const originalWorkbenchPaint=paint; paint=function(p){originalWorkbenchPaint(p);q('#privacy').textContent='Privacy: '+(p.privacy?.browser_binding||'loopback_only')+' browser; '+(p.privacy?.public_support||'explicit_redacted_export_only')+'.';(p.jobs||[]).filter(j=>j.state==='waiting_human').forEach(j=>{let cards=[...document.querySelectorAll('#jobs .tile')];let card=cards.find(x=>x.textContent.includes(j.job_id));if(card&&!card.querySelector('.observation')){let b=document.createElement('button');b.className='button observation';b.textContent='Record observation';b.onclick=()=>observe(j.job_id);card.appendChild(b)}})};
     const paintWithEvidence=paint; paint=function(p){paintWithEvidence(p);decorateWorkbenchEvidence(p)};
     (async()=>{try{let s=await get('/api/v1/workbench/security');token=s.browser_token;await refresh();setInterval(refresh,5000)}catch(e){q('#raw').textContent='Workbench startup failed: '+JSON.stringify(e)}})();
    function applyStoryTopology(p){if(advanced)return;const labels={workbench:'Workbench',docker:'Container engine',runner:'Host runner',valheim:'Game install','dev-mcp':'Development MCP',gateway:'Gateway',am4:'Server',omen:'Rendered client A',i5:'Rendered client B',p7:'Cloud release edge'};const roles={workbench:'human cockpit',docker:'local container runtime',runner:'bounded local execution',valheim:'local game installation','dev-mcp':'development/lab control plane',gateway:'release, telemetry, and control edge',am4:'dedicated game server',omen:'primary rendered client',i5:'second rendered client',p7:'promotion and release edge'};const cards=[...document.querySelectorAll('#topology .tile')];(p.topology?.nodes||[]).forEach(n=>{const card=cards.find(x=>x.textContent.includes(n.title));if(!card)return;const h=card.querySelector('h3');if(h)h.textContent=labels[n.id]||n.title;const paragraphs=card.querySelectorAll('p');if(paragraphs[0])paragraphs[0].innerHTML=esc(roles[n.id]||'declared component')+'<br>human touch: '+esc(n.human_touch);if(paragraphs[1])paragraphs[1].textContent='Story view · observed '+(n.observed_utc||'not observed')});}
    const paintWithStoryTopology=paint;paint=function(p){paintWithStoryTopology(p);applyStoryTopology(p)};
    function applyStorySurface(p){if(advanced)return;const targetLabels={local:'this machine',remote:'configured remote edge',AM4:'server',OMEN:'rendered client A',i5:'rendered client B',P7:'cloud release edge'};const capabilityCards=[...document.querySelectorAll('#build-caps .tile,#operate-caps .tile,#recover-caps .tile')];(p.capabilities||[]).forEach(c=>{const card=capabilityCards.find(x=>x.textContent.includes(c.id));if(!card)return;const paragraphs=card.querySelectorAll('p');if(paragraphs[1])paragraphs[1].innerHTML='profiles: '+esc((c.eligible_profiles||[]).join(', '))+'<br>targets: '+esc((c.eligible_targets||[]).map(t=>targetLabels[t]||'declared lane').join(', '))+'<br>privacy: '+esc(c.privacy_class||'private_local')});const jobCards=[...document.querySelectorAll('#jobs .tile')];(p.jobs||[]).forEach(j=>{const card=jobCards.find(x=>x.textContent.includes(j.job_id));if(!card)return;const paragraph=card.querySelector('p');if(paragraph)paragraph.innerHTML=esc(j.job_id)+'<br>'+esc(j.capability_id)+' · '+esc(targetLabels[j.target]||'declared lane')})}
    const paintWithStorySurface=paint;paint=function(p){paintWithStorySurface(p);applyStorySurface(p)};
  </script>
</body>
</html>
""";
}
