// <auto-generated />
using System;
using Game.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Game.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260328154322_NatureTwoPointZero")]
    partial class NatureTwoPointZero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Game.Persistence.Entities.ChallengeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProgressMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("progress_mode");

                    b.Property<string>("Rewards")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rewards");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_event");

                    b.Property<string>("TriggerFilters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trigger_filters");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset?>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("TriggerEvent");

                    b.ToTable("challenges", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.ChallengeProgressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("challenge_id");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer")
                        .HasColumnName("current_value");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "GuildId")
                        .IsUnique();

                    b.ToTable("challenge_progress", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.ContainerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_id");

                    b.Property<string>("StructureId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("structure_id");

                    b.HasKey("Id");

                    b.ToTable("containers", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.ContainerItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("container_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stored_at");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("container_items", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("GuildId")
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("RegionId")
                        .HasColumnType("text")
                        .HasColumnName("region_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_service");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.GuildProgressEntity", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<int>("ChallengesCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("challenges_completed");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GuildId");

                    b.ToTable("guild_progress", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.NaturalResourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GrowthHistory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("growth_history");

                    b.Property<double>("Health")
                        .HasColumnType("double precision")
                        .HasColumnName("health");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<double>("LeanX")
                        .HasColumnType("double precision")
                        .HasColumnName("lean_x");

                    b.Property<double>("LeanZ")
                        .HasColumnType("double precision")
                        .HasColumnName("lean_z");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<double>("PositionZ")
                        .HasColumnType("double precision")
                        .HasColumnName("position_z");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_id");

                    b.Property<double>("RegrowthProgress")
                        .HasColumnType("double precision")
                        .HasColumnName("regrowth_progress");

                    b.Property<double>("StumpHealth")
                        .HasColumnType("double precision")
                        .HasColumnName("stump_health");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("natural_resources", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.PlayerInventoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_inventories", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.PlayerProgressEntity", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlayerId");

                    b.ToTable("player_progress", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.RegionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<double>("BoundsMaxX")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_max_x");

                    b.Property<double>("BoundsMaxY")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_max_y");

                    b.Property<double>("BoundsMaxZ")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_max_z");

                    b.Property<double>("BoundsMinX")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_min_x");

                    b.Property<double>("BoundsMinY")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_min_y");

                    b.Property<double>("BoundsMinZ")
                        .HasColumnType("double precision")
                        .HasColumnName("bounds_min_z");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("TickRate")
                        .HasColumnType("double precision")
                        .HasColumnName("tick_rate");

                    b.HasKey("Id");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.RegionProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AltitudeGrid")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("altitude_grid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GeologicHistory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("geologic_history");

                    b.Property<int>("GridHeight")
                        .HasColumnType("integer")
                        .HasColumnName("grid_height");

                    b.Property<int>("GridWidth")
                        .HasColumnType("integer")
                        .HasColumnName("grid_width");

                    b.Property<string>("HumidityGrid")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("humidity_grid");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_id");

                    b.Property<double>("TradeWindX")
                        .HasColumnType("double precision")
                        .HasColumnName("trade_wind_x");

                    b.Property<double>("TradeWindZ")
                        .HasColumnType("double precision")
                        .HasColumnName("trade_wind_z");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("region_profiles", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.StructureEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<double>("PositionZ")
                        .HasColumnType("double precision")
                        .HasColumnName("position_z");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_id");

                    b.Property<double>("Rotation")
                        .HasColumnType("double precision")
                        .HasColumnName("rotation");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RegionId");

                    b.ToTable("structures", (string)null);
                });

            modelBuilder.Entity("Game.Persistence.Entities.WorldItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<double>("PositionZ")
                        .HasColumnType("double precision")
                        .HasColumnName("position_z");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_id");

                    b.Property<DateTimeOffset>("SpawnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spawned_at");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("world_items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
