// AUTO-GENERATED by tools/export-class-colors.js — DO NOT EDIT.
// Source: src/overlay/builtins/player-dots.overlay.jsx (OKLCH → sRGB).
// Regenerate: node tools/export-class-colors.js > path/to/WowClassColors.generated.cs

using Godot;
using System.Collections.Generic;

namespace CommunitySurvival.Replay;

public static class WowClassColors
{
    private static readonly Dictionary<string, Color> ClassMap = new()
    {
        { "DeathKnight", new Color(0.7220f, 0.2668f, 0.3320f) }, // oklch(55% 0.15 15)
        { "DemonHunter", new Color(0.5393f, 0.2396f, 0.6059f) }, // oklch(50% 0.16 320)
        { "Druid", new Color(0.8421f, 0.4362f, 0.0143f) }, // oklch(65% 0.16 55)
        { "Evoker", new Color(0.0000f, 0.6039f, 0.5151f) }, // oklch(60% 0.14 180)
        { "Hunter", new Color(0.4178f, 0.6728f, 0.3614f) }, // oklch(68% 0.13 140)
        { "Mage", new Color(0.2402f, 0.7496f, 0.8871f) }, // oklch(75% 0.12 220)
        { "Monk", new Color(0.0000f, 0.7280f, 0.5685f) }, // oklch(70% 0.14 170)
        { "Paladin", new Color(0.9773f, 0.5886f, 0.6501f) }, // oklch(78% 0.12 10)
        { "Priest", new Color(0.8751f, 0.8952f, 0.9508f) }, // oklch(92% 0.02 270)
        { "Rogue", new Color(0.8724f, 0.7646f, 0.3436f) }, // oklch(82% 0.13 95)
        { "Shaman", new Color(0.0000f, 0.4650f, 0.7816f) }, // oklch(55% 0.16 245)
        { "Warlock", new Color(0.4732f, 0.3666f, 0.7278f) }, // oklch(55% 0.14 295)
        { "Warrior", new Color(0.7204f, 0.5091f, 0.3335f) }, // oklch(65% 0.09 60)
    };

    private static readonly Dictionary<string, Color> RoleMap = new()
    {
        { "Tank", new Color(0.1451f, 0.4739f, 0.6702f) }, // oklch(55% 0.11 240)
        { "Healer", new Color(0.3037f, 0.5753f, 0.3183f) }, // oklch(60% 0.12 145)
        { "MeleeDps", new Color(0.7487f, 0.3321f, 0.2738f) }, // oklch(58% 0.14 30)
        { "RangedDps", new Color(0.5260f, 0.4588f, 0.8304f) }, // oklch(62% 0.14 290)
    };

    public static readonly Color Neutral = new Color(0.4686f, 0.5075f, 0.5492f); // oklch(60% 0.02 250)
    public static readonly Color Boss = new Color(0.1503f, 0.1833f, 0.2183f);       // oklch(30% 0.020 250)
    public static readonly Color Add = new Color(0.6082f, 0.4648f, 0.4150f);         // oklch(60% 0.05 40)

    public static readonly HashSet<string> KnownClasses = new(ClassMap.Keys);

    // Class first, role fallback, neutral last — matches colorFor() in the
    // canonical 2D overlay.
    public static Color For(string entityClass, string entityRole)
    {
        if (entityClass != null && ClassMap.TryGetValue(entityClass, out var c)) return c;
        if (entityRole != null && RoleMap.TryGetValue(entityRole, out var r)) return r;
        return Neutral;
    }
}
